// UI chrome is multilingual (English / Telugu / Hindi / Tamil / Malayalam / Sanskrit) to demonstrate the multilingual
// architecture end-to-end. Generated legal answers are translated live via
// the backend's translation pipeline (see backend/app/translate.py); if that
// service is unreachable, the UI shows a visible "translation unavailable"
// note rather than silently displaying the wrong language.
export const COPY = {
  en: {
    appName: 'SUTRADHARA',
    tagline: 'AI-Powered IP & Regulatory Intelligence for Ayurveda',
    team: 'Team Chaturya',
    heroLede:
      'The platform connects Ayurvedic products with applicable intellectual-property regimes, regulatory requirements, jurisdiction-specific rules, and authoritative evidence.',
    heroCta: 'Analyze an Ayurvedic Product',

    navAnalyze: 'Analyze',
    navAbs: 'ABS Compliance',
    navTkdl: 'TKDL Check',
    navEvidence: 'Evidence',
    navGraph: 'Knowledge Graph',
    navEval: 'Evaluation',

    inputLabel: 'Describe your Ayurvedic product or IP question',
    placeholder: 'e.g. Can I patent a classical Ayurvedic formulation already described in a traditional text?',
    analyze: 'Analyze',
    analyzing: 'Analyzing…',
    india: 'India',
    international: 'International',
    disclaimer: 'Information, not legal advice.',
    classification: 'Product Classification',
    jurisdiction: 'Jurisdiction',
    applicableAreas: 'Applicable IP & Regulatory Areas',
    assessment: 'AI Assessment',
    sources: 'Evidence & Citations',
    confidence: 'Evidence Confidence',
    escalate: 'Escalate to IP Facilitator',
    needExpert: 'Need expert assistance?',
    detectedLanguage: 'Detected input language',
    retrievalNote: 'Retrieval normalized to',
    evidenceBoundary: 'Evidence Boundary',
    evidenceBoundaryBody: 'Insufficient authoritative evidence to provide a reliable answer.',
    whyAbstained: 'Why the system abstained',
    systemError: 'Analysis service temporarily unavailable. Please try again in a moment.',

    evidencePageTitle: 'Evidence Explorer',
    evidencePageLede: 'Where did the last answer come from? Every source below was actually retrieved from the authoritative corpus for your most recent analysis — nothing here is invented.',
    evidenceEmpty: 'Run an analysis first — retrieved sources for that query will appear here.',

    graphEmpty: 'Knowledge graph data is unavailable from the backend right now.',
    evalEmpty: 'No queries logged yet in this session.',

    absTitle: 'ABS Compliance Check',
    absLede: 'Checks whether a query is likely to trigger Access-and-Benefit-Sharing obligations under the Biological Diversity Act, CBD, and the Nagoya Protocol — and what evidence supports that.',
    absPlaceholder: 'e.g. We want to commercialize a formulation using a biological resource sourced from a specific region in India',
    absButton: 'Check ABS Compliance',
    absEmpty: 'Describe the product or sourcing scenario above to see the ABS checklist here.',
    absNotTriggered: 'No clear Access-and-Benefit-Sharing signal was found for this query. This does not rule ABS out — describe the biological resource and its provenance for a more specific check.',

    tkdlTitle: 'TKDL / Prior-Art Check',
    tkdlLede: 'Points to the Traditional Knowledge Digital Library workflow relevant to a classical formulation, and surfaces the prior-art sources the system found.',
    tkdlPlaceholder: 'e.g. Is this formulation already documented as traditional knowledge in a classical text?',
    tkdlButton: 'Check TKDL / Prior Art',
    tkdlEmpty: 'Describe the formulation above to see the Traditional Knowledge pointer and related sources here.',
    tkdlNotTriggered: 'No Traditional Knowledge pointer was generated for this query — it may not be classified as classical/generic, or no TK-related source was retrieved.',

    languageEnglish: 'English', languageTelugu: 'తెలుగు', languageHindi: 'हिन्दी', languageTamil: 'தமிழ்', languageMalayalam: 'മലയാളം', languageSanskrit: 'संस्कृतम्', primaryNavigation: 'Primary navigation', loadingAnalysis: 'Loading analysis',
    analysisHelper: 'Source-grounded analysis across the selected jurisdiction', jurisdictionPrefix: 'JURISDICTION',
    clarificationCategories: ['Classical / Generic Medicine', 'Patent / Proprietary Medicine', 'New / Non-Classical Drug', 'Phytopharmaceutical', 'Ayurveda-Aahar / Nutraceutical', 'Cosmetic'],
    paraphraseVerified: 'phrased via Groq · citations verified', translationUnavailableAnswer: 'Translation service unavailable right now — showing the English answer.',
    tkPointer: 'Traditional Knowledge / Prior-Art Pointer', absConsiderations: 'Potential ABS Considerations',
    absChecklist: { biologicalResource: 'Biological resource involved', provenance: 'Source/provenance identified', framework: 'Relevant ABS framework identified', source: 'Supporting source retrieved' },
    confidenceSupport: 'How strongly the retained sources support this analysis', compositeConfidence: 'composite confidence', confidenceScale: 'confidence scale',
    confidenceFactors: { retrieval_relevance: 'Retrieval relevance', source_count_factor: 'Source count', source_authority: 'Source authority', agreement: 'Domain agreement', classification_confidence: 'Classification confidence' },
    confidenceNote: 'Composite score computed from retrieval and classification signals actually produced by this analysis — never a fabricated accuracy figure.',
    translationUnavailableMessage: 'Translation service unavailable right now — showing the English message.', evidenceBoundaryReason: 'The retained evidence set was empty or its combined confidence fell below the safe-answer threshold — so the system is declining to answer rather than guess.',
    sourceLabel: 'SOURCE', matchLabel: 'match', sourceFields: { authority: 'Authority', domain: 'Domain', type: 'Source type', version: 'Version', retrieved: 'Retrieved', precision: 'Precision' }, viewSource: 'View source',
    builtFor: 'Built for the Ministry of AYUSH & All India Institute of Ayurveda', liveEvidenceTrail: 'A live evidence trail', heroTraceTitle: 'From product to provision, with the chain visible.', heroTraceBody: 'SUTRADHARA classifies the question, routes the relevant regime, and keeps the source in view.', citationGrounded: 'Citation-grounded by design',
    heroTrace: [{ label: 'Product query', value: 'Ashwagandha extract with a novel process' }, { label: 'Classification', value: 'Phytopharmaceutical / biological resource' }, { label: 'Evidence route', value: 'Biological Diversity Act, 2002 · Section 7' }], sourceRetained: 'Source retained', confidenceHigh: 'Confidence: high',
    focusedTool: 'Focused research tool', working: 'Working…', absChecklistLabel: 'ABS checklist', tkdlPointerLabel: 'TKDL pointer', preview: 'preview',
    reviewPathway: 'Human review pathway', escalateTitle: 'Escalate to IP Facilitator', escalationDescription: 'A human facilitator will review this query along with the evidence retrieved below.', escalationRecorded: 'Escalation recorded.', escalationFollowUp: 'A facilitator will follow up using the context below.',
    escalationFields: { query: 'Query', category: 'Category', jurisdiction: 'Jurisdiction', areas: 'Areas', sources: 'Sources' }, noSources: 'none', contactEmail: 'Contact email (optional)', emailPlaceholder: 'you@example.com', escalationError: 'Could not reach the escalation service — please try again.', cancel: 'Cancel', sending: 'Sending…', submit: 'Submit',
    graphGrounding: 'How the answer is grounded', explainabilityGraph: 'Explainability Graph', graphLegend: { query: 'Query context', regulatory: 'Regulatory structure', traditional: 'Traditional knowledge', authoritative: 'Authoritative source' },
    classificationCategories: { 'Classical / Generic Medicine': 'Classical / Generic Medicine', 'Patent / Proprietary Medicine': 'Patent / Proprietary Medicine', 'New / Non-Classical Drug': 'New / Non-Classical Drug', Phytopharmaceutical: 'Phytopharmaceutical', 'Ayurveda-Aahar / Nutraceutical': 'Ayurveda-Aahar / Nutraceutical', Cosmetic: 'Cosmetic' }, areaLabels: { Patents: 'Patents', 'Geographical Indications': 'Geographical Indications', Trademarks: 'Trademarks', Copyright: 'Copyright', Designs: 'Designs', 'Trade Secrets': 'Trade Secrets', 'Plant Variety Protection': 'Plant Variety Protection', 'Traditional Knowledge': 'Traditional Knowledge', 'Access-and-Benefit-Sharing': 'Access-and-Benefit-Sharing', 'Drug regulation': 'Drug regulation', Advertising: 'Advertising', Labelling: 'Labelling', 'Food / nutraceutical regulation': 'Food / nutraceutical regulation', 'Cosmetic regulation': 'Cosmetic regulation' },
    graphNodes: { product: 'Ayurvedic Product', category: 'Product Category', tk: 'Traditional Knowledge', regime: 'IP/Regulatory Regime', law: 'Governing Law', provision: 'Provision', source: 'Authoritative Source' }, graphEdges: { product_category: 'belongs to', category_regime: 'relevant to', category_tk: 'may reference', regime_law: 'governed by', law_provision: 'contains', provision_source: 'supported by' },
    eval: { observability: 'System observability', title: 'Evaluation Dashboard', chartLabel: 'Confidence history chart', chartTitle: 'Confidence over logged queries', observations: 'observations', chartEmpty: 'Confidence history will trace here after the first analysis.', queryStart: 'query 01', queryLatest: 'latest query', totalQueries: 'Total queries logged', safeAbstention: 'Safe-abstention rate', averageConfidence: 'Average confidence', answerAccuracy: 'Answer accuracy', citationCorrectness: 'Citation correctness', classificationAccuracy: 'Classification accuracy', multilingualQuality: 'Multilingual response quality', pending: 'Evaluation pending', manualReviewSet: 'Evaluation pending — requires manual review against the verified test set', manualReview: 'Evaluation pending — requires manual review', emptyTitle: 'Your evidence trail starts here.', emptyBody: 'Run an analysis to populate confidence history, citation checks, and classification review.', citationReview: 'citation review', note: 'Evaluation pending — no queries logged yet.' },
  },
  te: {
    appName: 'సూత్రధార',
    tagline: 'ఆయుర్వేదం కోసం AI-ఆధారిత మేధో సంపత్తి & నియంత్రణ మేధస్సు',
    team: 'టీమ్ చతుర్య',
    heroLede:
      'ఈ వేదిక ఆయుర్వేద ఉత్పత్తులను వర్తించే మేధో సంపత్తి పాలనలు, నియంత్రణ అవసరాలు, అధికార-పరిధి నిర్దిష్ట నియమాలు మరియు అధికారిక ఆధారాలతో అనుసంధానిస్తుంది.',
    heroCta: 'ఆయుర్వేద ఉత్పత్తిని విశ్లేషించండి',

    navAnalyze: 'విశ్లేషణ',
    navAbs: 'ABS అనుసరణ',
    navTkdl: 'TKDL పరిశీలన',
    navEvidence: 'ఆధారాలు',
    navGraph: 'జ్ఞాన గ్రాఫ్',
    navEval: 'మూల్యాంకనం',

    inputLabel: 'మీ ఆయుర్వేద ఉత్పత్తి లేదా IP ప్రశ్నను వివరించండి',
    placeholder: 'ఉదా. సాంప్రదాయ గ్రంథంలో వివరించిన శాస్త్రీయ ఆయుర్వేద సూత్రీకరణకు నేను పేటెంట్ పొందవచ్చా?',
    analyze: 'విశ్లేషించండి',
    analyzing: 'విశ్లేషిస్తోంది…',
    india: 'భారతదేశం',
    international: 'అంతర్జాతీయ',
    disclaimer: 'ఇది సమాచారం మాత్రమే, న్యాయ సలహా కాదు.',
    classification: 'ఉత్పత్తి వర్గీకరణ',
    jurisdiction: 'అధికార పరిధి',
    applicableAreas: 'వర్తించే IP & నియంత్రణ అంశాలు',
    assessment: 'AI మదింపు',
    sources: 'ఆధారాలు & ఉల్లేఖనలు',
    confidence: 'ఆధార విశ్వసనీయత',
    escalate: 'IP సదుపాయకుడికి తెలియజేయండి',
    needExpert: 'నిపుణుల సహాయం కావాలా?',
    detectedLanguage: 'గుర్తించిన ఇన్‌పుట్ భాష',
    retrievalNote: 'రిట్రీవల్ కోసం సాధారణీకరించబడింది',
    evidenceBoundary: 'ఆధార పరిమితి',
    evidenceBoundaryBody: 'నమ్మదగిన సమాధానం ఇవ్వడానికి తగినంత అధికారిక ఆధారాలు లేవు.',
    whyAbstained: 'వ్యవస్థ ఎందుకు నిరాకరించింది',
    systemError: 'విశ్లేషణ సేవ తాత్కాలికంగా అందుబాటులో లేదు. దయచేసి కొద్దిసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.',

    evidencePageTitle: 'ఆధార అన్వేషణ',
    evidencePageLede: 'చివరి సమాధానం ఎక్కడ నుండి వచ్చింది? మీ ఇటీవలి విశ్లేషణ కోసం క్రింద ఉన్న ప్రతి మూలం అధికారిక కార్పస్ నుండి నిజంగా పొందబడింది.',
    evidenceEmpty: 'ముందుగా ఒక విశ్లేషణ నడపండి — ఆ ప్రశ్న కోసం పొందిన మూలాలు ఇక్కడ కనిపిస్తాయి.',

    graphEmpty: 'ప్రస్తుతం బ్యాకెండ్ నుండి నాలెడ్జ్ గ్రాఫ్ డేటా అందుబాటులో లేదు.',
    evalEmpty: 'ఈ సెషన్‌లో ఇంకా ప్రశ్నలు నమోదు కాలేదు.',

    absTitle: 'ABS అనుసరణ పరిశీలన',
    absLede: 'జీవవైవిధ్య చట్టం, CBD మరియు నాగోయా ప్రోటోకాల్ కింద యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్ బాధ్యతలను ప్రశ్న ప్రేరేపించే అవకాశం ఉందో లేదో పరిశీలిస్తుంది.',
    absPlaceholder: 'ఉదా. భారతదేశంలోని ఒక నిర్దిష్ట ప్రాంతం నుండి పొందిన జీవ వనరును ఉపయోగించి సూత్రీకరణను వాణిజ్యీకరించాలనుకుంటున్నాము',
    absButton: 'ABS అనుసరణను పరిశీలించండి',
    absEmpty: 'ABS చెక్‌లిస్ట్‌ను చూడటానికి పైన ఉత్పత్తి లేదా సోర్సింగ్ దృశ్యాన్ని వివరించండి.',
    absNotTriggered: 'ఈ ప్రశ్న కోసం స్పష్టమైన యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్ సంకేతం కనుగొనబడలేదు. ఇది ABSను పూర్తిగా తోసిపుచ్చదు — మరింత నిర్దిష్టమైన పరిశీలన కోసం జీవ వనరు మరియు దాని మూలాన్ని వివరించండి.',

    tkdlTitle: 'TKDL / ముందస్తు-కళ పరిశీలన',
    tkdlLede: 'శాస్త్రీయ సూత్రీకరణకు సంబంధించిన సాంప్రదాయ జ్ఞాన డిజిటల్ లైబ్రరీ వర్క్‌ఫ్లోను సూచిస్తుంది మరియు వ్యవస్థ కనుగొన్న ముందస్తు-కళ మూలాలను చూపిస్తుంది.',
    tkdlPlaceholder: 'ఉదా. ఈ సూత్రీకరణ ఇప్పటికే ఒక శాస్త్రీయ గ్రంథంలో సాంప్రదాయ జ్ఞానంగా నమోదు చేయబడిందా?',
    tkdlButton: 'TKDL / ముందస్తు-కళను పరిశీలించండి',
    tkdlEmpty: 'సాంప్రదాయ జ్ఞాన సూచన మరియు సంబంధిత మూలాలను చూడటానికి పైన సూత్రీకరణను వివరించండి.',
    tkdlNotTriggered: 'ఈ ప్రశ్న కోసం సాంప్రదాయ జ్ఞాన సూచన రూపొందించబడలేదు — ఇది శాస్త్రీయ/సాధారణంగా వర్గీకరించబడకపోవచ్చు, లేదా TK-సంబంధిత మూలం పొందబడలేదు.',

    languageEnglish: 'ఇంగ్లీష్', languageTelugu: 'తెలుగు', languageHindi: 'హిందీ', languageTamil: 'తమిళ్', languageMalayalam: 'మలయాళం', languageSanskrit: 'సంస్కృతం', primaryNavigation: 'ప్రధాన నావిగేషన్', loadingAnalysis: 'విశ్లేషణ లోడ్ అవుతోంది',
    analysisHelper: 'ఎంచుకున్న అధికార పరిధిలో ఆధారాలతో కూడిన విశ్లేషణ', jurisdictionPrefix: 'అధికార పరిధి',
    clarificationCategories: ['శాస్త్రీయ / సాధారణ ఔషధం', 'పేటెంట్ / స్వంత ఔషధం', 'కొత్త / శాస్త్రీయేతర ఔషధం', 'ఫైటోఫార్మాస్యూటికల్', 'ఆయుర్వేద-ఆహార / న్యూట్రాస్యూటికల్', 'కాస్మెటిక్'],
    paraphraseVerified: 'Groq ద్వారా రూపుదిద్దబడింది · ఉల్లేఖనలు ధృవీకరించబడ్డాయి', translationUnavailableAnswer: 'అనువాద సేవ ప్రస్తుతం అందుబాటులో లేదు — ఇంగ్లీష్ సమాధానం చూపబడుతోంది.',
    tkPointer: 'సాంప్రదాయ జ్ఞానం / ముందస్తు-కళ సూచన', absConsiderations: 'సంభావ్య ABS పరిశీలనలు',
    absChecklist: { biologicalResource: 'జీవ వనరు ఉంది', provenance: 'మూలం / ప్రోవెనెన్స్ గుర్తించబడింది', framework: 'సంబంధిత ABS ఫ్రేమ్‌వర్క్ గుర్తించబడింది', source: 'మద్దతు మూలం పొందబడింది' },
    confidenceSupport: 'నిలుపుకున్న మూలాలు ఈ విశ్లేషణకు ఎంత బలంగా మద్దతు ఇస్తున్నాయి', compositeConfidence: 'సమ్మిళిత విశ్వసనీయత', confidenceScale: 'విశ్వసనీయత స్థాయి',
    confidenceFactors: { retrieval_relevance: 'రిట్రీవల్ సంబంధితత', source_count_factor: 'మూలాల సంఖ్య', source_authority: 'మూల అధికారికత', agreement: 'డొమైన్ సమ్మతి', classification_confidence: 'వర్గీకరణ విశ్వసనీయత' },
    confidenceNote: 'ఈ విశ్లేషణలో నిజంగా ఉత్పత్తి అయిన రిట్రీవల్ మరియు వర్గీకరణ సంకేతాల ఆధారంగా సమ్మిళిత స్కోరు లెక్కించబడుతుంది — కల్పిత ఖచ్చితత్వం కాదు.',
    translationUnavailableMessage: 'అనువాద సేవ ప్రస్తుతం అందుబాటులో లేదు — ఇంగ్లీష్ సందేశం చూపబడుతోంది.', evidenceBoundaryReason: 'నిలుపుకున్న ఆధారాల సమితి ఖాళీగా ఉంది లేదా దాని సమ్మిళిత విశ్వసనీయత సురక్షిత సమాధాన పరిమితి కంటే తక్కువగా ఉంది — అందువల్ల వ్యవస్థ ఊహించి సమాధానం ఇవ్వడం లేదు.',
    sourceLabel: 'మూలం', matchLabel: 'సరిపోలిక', sourceFields: { authority: 'అధికారికత', domain: 'డొమైన్', type: 'మూల రకం', version: 'వెర్షన్', retrieved: 'పొందిన తేదీ', precision: 'ఖచ్చితత్వం' }, viewSource: 'మూలాన్ని చూడండి',
    builtFor: 'ఆయుష్ మంత్రిత్వ శాఖ & ఆల్ ఇండియా ఇన్‌స్టిట్యూట్ ఆఫ్ ఆయుర్వేదం కోసం నిర్మించబడింది', liveEvidenceTrail: 'ప్రత్యక్ష ఆధార మార్గం', heroTraceTitle: 'ఉత్పత్తి నుండి నిబంధన వరకు, మొత్తం మార్గం కనిపిస్తుంది.', heroTraceBody: 'SUTRADHARA ప్రశ్నను వర్గీకరిస్తుంది, సంబంధిత పాలనకు మార్గనిర్దేశం చేస్తుంది మరియు మూలాన్ని చూపిస్తుంది.', citationGrounded: 'ఉల్లేఖన ఆధారితం',
    heroTrace: [{ label: 'ఉత్పత్తి ప్రశ్న', value: 'కొత్త ప్రక్రియతో అశ్వగంధ సారం' }, { label: 'వర్గీకరణ', value: 'ఫైటోఫార్మాస్యూటికల్ / జీవ వనరు' }, { label: 'ఆధార మార్గం', value: 'జీవ వైవిధ్య చట్టం, 2002 · సెక్షన్ 7' }], sourceRetained: 'మూలం నిలుపబడింది', confidenceHigh: 'విశ్వసనీయత: అధిక',
    focusedTool: 'కేంద్రీకృత పరిశోధన సాధనం', working: 'పని జరుగుతోంది…', absChecklistLabel: 'ABS చెక్‌లిస్ట్', tkdlPointerLabel: 'TKDL సూచన', preview: 'పరిదృశ్యం',
    reviewPathway: 'మానవ సమీక్ష మార్గం', escalateTitle: 'IP సదుపాయకుడికి పంపండి', escalationDescription: 'మానవ సదుపాయకుడు ఈ ప్రశ్నను మరియు దిగువ పొందిన ఆధారాలను సమీక్షిస్తారు.', escalationRecorded: 'ఎస్కలేషన్ నమోదు చేయబడింది.', escalationFollowUp: 'దిగువ సందర్భాన్ని ఉపయోగించి సదుపాయకుడు మిమ్మల్ని సంప్రదిస్తారు.',
    escalationFields: { query: 'ప్రశ్న', category: 'వర్గం', jurisdiction: 'అధికార పరిధి', areas: 'అంశాలు', sources: 'మూలాలు' }, noSources: 'ఏవీ లేవు', contactEmail: 'సంప్రదింపు ఇమెయిల్ (ఐచ్ఛికం)', emailPlaceholder: 'you@example.com', escalationError: 'ఎస్కలేషన్ సేవను చేరుకోలేకపోయాం — మళ్లీ ప్రయత్నించండి.', cancel: 'రద్దు', sending: 'పంపుతోంది…', submit: 'సమర్పించండి',
    graphGrounding: 'సమాధానం ఎలా ఆధారపడింది', explainabilityGraph: 'వివరణాత్మక గ్రాఫ్', graphLegend: { query: 'ప్రశ్న సందర్భం', regulatory: 'నియంత్రణ నిర్మాణం', traditional: 'సాంప్రదాయ జ్ఞానం', authoritative: 'అధికారిక మూలం' },
    classificationCategories: { 'Classical / Generic Medicine': 'శాస్త్రీయ / సాధారణ ఔషధం', 'Patent / Proprietary Medicine': 'పేటెంట్ / స్వంత ఔషధం', 'New / Non-Classical Drug': 'కొత్త / శాస్త్రీయేతర ఔషధం', Phytopharmaceutical: 'ఫైటోఫార్మాస్యూటికల్', 'Ayurveda-Aahar / Nutraceutical': 'ఆయుర్వేద-ఆహార / న్యూట్రాస్యూటికల్', Cosmetic: 'కాస్మెటిక్' }, areaLabels: { Patents: 'పేటెంట్లు', 'Geographical Indications': 'భౌగోళిక సూచనలు', Trademarks: 'ట్రేడ్‌మార్క్‌లు', Copyright: 'కాపీరైట్', Designs: 'డిజైన్లు', 'Trade Secrets': 'వాణిజ్య రహస్యాలు', 'Plant Variety Protection': 'మొక్కల రకం రక్షణ', 'Traditional Knowledge': 'సాంప్రదాయ జ్ఞానం', 'Access-and-Benefit-Sharing': 'యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్', 'Drug regulation': 'ఔషధ నియంత్రణ', Advertising: 'ప్రకటనలు', Labelling: 'లేబులింగ్', 'Food / nutraceutical regulation': 'ఆహార / న్యూట్రాస్యూటికల్ నియంత్రణ', 'Cosmetic regulation': 'కాస్మెటిక్ నియంత్రణ' },
    graphNodes: { product: 'ఆయుర్వేద ఉత్పత్తి', category: 'ఉత్పత్తి వర్గం', tk: 'సాంప్రదాయ జ్ఞానం', regime: 'IP / నియంత్రణ పాలన', law: 'పాలక చట్టం', provision: 'నిబంధన', source: 'అధికారిక మూలం' }, graphEdges: { product_category: 'చెందుతుంది', category_regime: 'సంబంధితం', category_tk: 'సూచించవచ్చు', regime_law: 'చట్టం ద్వారా పాలితం', law_provision: 'కలిగి ఉంది', provision_source: 'మూలం మద్దతు' },
    eval: { observability: 'వ్యవస్థ పరిశీలన', title: 'మూల్యాంకన డ్యాష్‌బోర్డ్', chartLabel: 'విశ్వసనీయత చరిత్ర చార్ట్', chartTitle: 'లాగ్ చేసిన ప్రశ్నల విశ్వసనీయత', observations: 'పరిశీలనలు', chartEmpty: 'మొదటి విశ్లేషణ తర్వాత విశ్వసనీయత చరిత్ర ఇక్కడ కనిపిస్తుంది.', queryStart: 'ప్రశ్న 01', queryLatest: 'తాజా ప్రశ్న', totalQueries: 'మొత్తం లాగ్ చేసిన ప్రశ్నలు', safeAbstention: 'సురక్షిత నిరాకరణ రేటు', averageConfidence: 'సగటు విశ్వసనీయత', answerAccuracy: 'సమాధాన ఖచ్చితత్వం', citationCorrectness: 'ఉల్లేఖన ఖచ్చితత్వం', classificationAccuracy: 'వర్గీకరణ ఖచ్చితత్వం', multilingualQuality: 'బహుభాషా సమాధాన నాణ్యత', pending: 'మూల్యాంకనం పెండింగ్‌లో ఉంది', manualReviewSet: 'మూల్యాంకనం పెండింగ్‌లో ఉంది — ధృవీకరించిన పరీక్షా సమితితో మానవ సమీక్ష అవసరం', manualReview: 'మూల్యాంకనం పెండింగ్‌లో ఉంది — మానవ సమీక్ష అవసరం', emptyTitle: 'మీ ఆధార మార్గం ఇక్కడ ప్రారంభమవుతుంది.', emptyBody: 'విశ్వసనీయత చరిత్ర, ఉల్లేఖన తనిఖీలు మరియు వర్గీకరణ సమీక్షను నింపడానికి విశ్లేషణ నడపండి.', citationReview: 'ఉల్లేఖన సమీక్ష', note: 'మూల్యాంకనం పెండింగ్‌లో ఉంది — ఇంకా ప్రశ్నలు లాగ్ కాలేదు.' },
  },
  hi: {
    appName: 'सूत्रधार',
    tagline: 'आयुर्वेद के लिए AI-संचालित IP और नियामक बुद्धिमत्ता',
    team: 'टीम चातुर्य',
    heroLede: 'यह मंच आयुर्वेदिक उत्पादों को लागू बौद्धिक संपदा व्यवस्थाओं, नियामक आवश्यकताओं, क्षेत्राधिकार-विशिष्ट नियमों और आधिकारिक प्रमाणों से जोड़ता है।',
    heroCta: 'आयुर्वेदिक उत्पाद का विश्लेषण करें',

    navAnalyze: 'विश्लेषण',
    navAbs: 'ABS अनुपालन',
    navTkdl: 'TKDL जांच',
    navEvidence: 'प्रमाण',
    navGraph: 'ज्ञान ग्राफ',
    navEval: 'मूल्यांकन',

    inputLabel: 'अपने आयुर्वेदिक उत्पाद या IP प्रश्न का वर्णन करें',
    placeholder: 'उदा. क्या पारंपरिक ग्रंथ में वर्णित शास्त्रीय आयुर्वेदिक फॉर्मूलेशन का पेटेंट लिया जा सकता है?',
    analyze: 'विश्लेषण करें',
    analyzing: 'विश्लेषण हो रहा है…',
    india: 'भारत',
    international: 'अंतरराष्ट्रीय',
    disclaimer: 'यह जानकारी है, कानूनी सलाह नहीं।',
    classification: 'उत्पाद वर्गीकरण',
    jurisdiction: 'क्षेत्राधिकार',
    applicableAreas: 'लागू IP और नियामक क्षेत्र',
    assessment: 'AI आकलन',
    sources: 'प्रमाण और उद्धरण',
    confidence: 'प्रमाण विश्वसनीयता',
    escalate: 'IP सुविधा केंद्र को भेजें',
    needExpert: 'विशेषज्ञ सहायता चाहिए?',
    detectedLanguage: 'पहचानी गई इनपुट भाषा',
    retrievalNote: 'रिट्रीवल के लिए सामान्यीकृत',
    evidenceBoundary: 'प्रमाण सीमा',
    evidenceBoundaryBody: 'विश्वसनीय उत्तर देने के लिए पर्याप्त आधिकारिक प्रमाण उपलब्ध नहीं है।',
    whyAbstained: 'प्रणाली ने उत्तर क्यों रोका',
    systemError: 'विश्लेषण सेवा अभी अस्थायी रूप से अनुपलब्ध है। कृपया कुछ देर बाद फिर प्रयास करें।',

    evidencePageTitle: 'प्रमाण अन्वेषक',
    evidencePageLede: 'पिछला उत्तर कहाँ से आया? नीचे दिया गया प्रत्येक स्रोत आपके नवीनतम विश्लेषण के लिए आधिकारिक कॉर्पस से प्राप्त किया गया है।',
    evidenceEmpty: 'पहले विश्लेषण चलाएँ — उस प्रश्न के प्राप्त स्रोत यहाँ दिखाई देंगे।',

    graphEmpty: 'इस समय बैकएंड से ज्ञान ग्राफ डेटा उपलब्ध नहीं है।',
    evalEmpty: 'इस सत्र में अभी तक कोई प्रश्न लॉग नहीं हुआ है।',

    absTitle: 'ABS अनुपालन जांच',
    absLede: 'यह जांचता है कि कोई प्रश्न जैव विविधता अधिनियम, CBD और नागोया प्रोटोकॉल के तहत Access-and-Benefit-Sharing दायित्व शुरू कर सकता है या नहीं।',
    absPlaceholder: 'उदा. हम भारत के किसी क्षेत्र से प्राप्त जैविक संसाधन का उपयोग करने वाले फॉर्मूलेशन का व्यावसायीकरण करना चाहते हैं',
    absButton: 'ABS अनुपालन जांचें',
    absEmpty: 'ABS चेकलिस्ट देखने के लिए ऊपर उत्पाद या सोर्सिंग स्थिति का वर्णन करें।',
    absNotTriggered: 'इस प्रश्न में ABS का स्पष्ट संकेत नहीं मिला। यह ABS को पूरी तरह नकारता नहीं है — अधिक विशिष्ट जांच के लिए जैविक संसाधन और उसका स्रोत बताएं।',

    tkdlTitle: 'TKDL / पूर्व कला जांच',
    tkdlLede: 'यह शास्त्रीय फॉर्मूलेशन से संबंधित Traditional Knowledge Digital Library प्रक्रिया और मिले हुए पूर्व कला स्रोत दिखाता है।',
    tkdlPlaceholder: 'उदा. क्या यह फॉर्मूलेशन पहले से किसी शास्त्रीय ग्रंथ में पारंपरिक ज्ञान के रूप में दर्ज है?',
    tkdlButton: 'TKDL / पूर्व कला जांचें',
    tkdlEmpty: 'TKDL संकेत और संबंधित स्रोत देखने के लिए ऊपर फॉर्मूलेशन का वर्णन करें।',
    tkdlNotTriggered: 'इस प्रश्न के लिए पारंपरिक ज्ञान संकेत नहीं बनाया गया — यह शास्त्रीय/सामान्य श्रेणी में नहीं आता हो सकता है या कोई संबंधित स्रोत नहीं मिला।',

    languageEnglish: 'अंग्रेज़ी', languageTelugu: 'तेलुगु', languageHindi: 'हिन्दी', languageTamil: 'तमिल', languageMalayalam: 'मलयालम', languageSanskrit: 'संस्कृतम्', primaryNavigation: 'मुख्य नेविगेशन', loadingAnalysis: 'विश्लेषण लोड हो रहा है',
    analysisHelper: 'चयनित क्षेत्राधिकार में प्रमाण-आधारित विश्लेषण', jurisdictionPrefix: 'क्षेत्राधिकार',
    clarificationCategories: ['शास्त्रीय / सामान्य औषधि', 'पेटेंट / स्वामित्व वाली औषधि', 'नई / गैर-शास्त्रीय औषधि', 'फाइटोफार्मास्यूटिकल', 'आयुर्वेद-आहार / न्यूट्रास्यूटिकल', 'कॉस्मेटिक'],
    paraphraseVerified: 'Groq द्वारा रूपांतरित · उद्धरण सत्यापित', translationUnavailableAnswer: 'अनुवाद सेवा अभी उपलब्ध नहीं है — अंग्रेज़ी उत्तर दिखाया जा रहा है।',
    tkPointer: 'पारंपरिक ज्ञान / पूर्व कला संकेत', absConsiderations: 'संभावित ABS विचार',
    absChecklist: { biologicalResource: 'जैविक संसाधन शामिल है', provenance: 'स्रोत / उत्पत्ति पहचानी गई', framework: 'संबंधित ABS ढांचा पहचाना गया', source: 'समर्थन स्रोत प्राप्त हुआ' },
    confidenceSupport: 'रखे गए स्रोत इस विश्लेषण का कितना मजबूत समर्थन करते हैं', compositeConfidence: 'समग्र विश्वसनीयता', confidenceScale: 'विश्वसनीयता पैमाना',
    confidenceFactors: { retrieval_relevance: 'रिट्रीवल प्रासंगिकता', source_count_factor: 'स्रोत संख्या', source_authority: 'स्रोत की प्रामाणिकता', agreement: 'डोमेन सहमति', classification_confidence: 'वर्गीकरण विश्वसनीयता' },
    confidenceNote: 'समग्र स्कोर इस विश्लेषण से प्राप्त रिट्रीवल और वर्गीकरण संकेतों से बनाया जाता है — यह कोई गढ़ी हुई सटीकता नहीं है।',
    translationUnavailableMessage: 'अनुवाद सेवा अभी उपलब्ध नहीं है — अंग्रेज़ी संदेश दिखाया जा रहा है।', evidenceBoundaryReason: 'रखे गए प्रमाण खाली थे या उनकी संयुक्त विश्वसनीयता सुरक्षित उत्तर सीमा से कम थी — इसलिए प्रणाली अनुमान लगाकर उत्तर देने से इनकार कर रही है।',
    sourceLabel: 'स्रोत', matchLabel: 'मिलान', sourceFields: { authority: 'प्राधिकरण', domain: 'डोमेन', type: 'स्रोत प्रकार', version: 'संस्करण', retrieved: 'प्राप्त', precision: 'सटीकता' }, viewSource: 'स्रोत देखें',
    builtFor: 'आयुष मंत्रालय और अखिल भारतीय आयुर्वेद संस्थान के लिए निर्मित', liveEvidenceTrail: 'एक जीवंत प्रमाण मार्ग', heroTraceTitle: 'उत्पाद से प्रावधान तक, पूरी श्रृंखला दिखाई देती है।', heroTraceBody: 'SUTRADHARA प्रश्न को वर्गीकृत करता है, संबंधित व्यवस्था तक पहुँचाता है और स्रोत को सामने रखता है।', citationGrounded: 'उद्धरण-आधारित प्रणाली',
    heroTrace: [{ label: 'उत्पाद प्रश्न', value: 'नई प्रक्रिया वाला अश्वगंधा अर्क' }, { label: 'वर्गीकरण', value: 'फाइटोफार्मास्यूटिकल / जैविक संसाधन' }, { label: 'प्रमाण मार्ग', value: 'जैव विविधता अधिनियम, 2002 · धारा 7' }], sourceRetained: 'स्रोत सुरक्षित', confidenceHigh: 'विश्वसनीयता: उच्च',
    focusedTool: 'केंद्रित शोध उपकरण', working: 'काम हो रहा है…', absChecklistLabel: 'ABS चेकलिस्ट', tkdlPointerLabel: 'TKDL संकेत', preview: 'पूर्वावलोकन',
    reviewPathway: 'मानव समीक्षा मार्ग', escalateTitle: 'IP सुविधा केंद्र को भेजें', escalationDescription: 'एक मानव सुविधाकर्ता नीचे प्राप्त प्रमाणों के साथ इस प्रश्न की समीक्षा करेगा।', escalationRecorded: 'एस्केलेशन दर्ज हो गया है।', escalationFollowUp: 'सुविधाकर्ता नीचे दिए गए संदर्भ के आधार पर आपसे संपर्क करेगा।',
    escalationFields: { query: 'प्रश्न', category: 'श्रेणी', jurisdiction: 'क्षेत्राधिकार', areas: 'क्षेत्र', sources: 'स्रोत' }, noSources: 'कोई नहीं', contactEmail: 'संपर्क ईमेल (वैकल्पिक)', emailPlaceholder: 'you@example.com', escalationError: 'एस्केलेशन सेवा तक नहीं पहुँच सके — कृपया फिर प्रयास करें।', cancel: 'रद्द करें', sending: 'भेजा जा रहा है…', submit: 'जमा करें',
    graphGrounding: 'उत्तर किस तरह प्रमाणित है', explainabilityGraph: 'व्याख्यात्मक ग्राफ', graphLegend: { query: 'प्रश्न संदर्भ', regulatory: 'नियामक संरचना', traditional: 'पारंपरिक ज्ञान', authoritative: 'आधिकारिक स्रोत' },
    classificationCategories: { 'Classical / Generic Medicine': 'शास्त्रीय / सामान्य औषधि', 'Patent / Proprietary Medicine': 'पेटेंट / स्वामित्व वाली औषधि', 'New / Non-Classical Drug': 'नई / गैर-शास्त्रीय औषधि', Phytopharmaceutical: 'फाइटोफार्मास्यूटिकल', 'Ayurveda-Aahar / Nutraceutical': 'आयुर्वेद-आहार / न्यूट्रास्यूटिकल', Cosmetic: 'कॉस्मेटिक' }, areaLabels: { Patents: 'पेटेंट', 'Geographical Indications': 'भौगोलिक संकेत', Trademarks: 'ट्रेडमार्क', Copyright: 'कॉपीराइट', Designs: 'डिज़ाइन', 'Trade Secrets': 'व्यापार रहस्य', 'Plant Variety Protection': 'पादप किस्म संरक्षण', 'Traditional Knowledge': 'पारंपरिक ज्ञान', 'Access-and-Benefit-Sharing': 'लाभ-साझाकरण', 'Drug regulation': 'औषधि नियमन', Advertising: 'विज्ञापन', Labelling: 'लेबलिंग', 'Food / nutraceutical regulation': 'खाद्य / न्यूट्रास्यूटिकल नियमन', 'Cosmetic regulation': 'कॉस्मेटिक नियमन' },
    graphNodes: { product: 'आयुर्वेदिक उत्पाद', category: 'उत्पाद श्रेणी', tk: 'पारंपरिक ज्ञान', regime: 'IP / नियामक व्यवस्था', law: 'शासी कानून', provision: 'प्रावधान', source: 'आधिकारिक स्रोत' }, graphEdges: { product_category: 'का हिस्सा है', category_regime: 'संबंधित है', category_tk: 'संदर्भित कर सकता है', regime_law: 'कानून द्वारा शासित', law_provision: 'इसमें शामिल है', provision_source: 'स्रोत द्वारा समर्थित' },
    eval: { observability: 'प्रणाली अवलोकन', title: 'मूल्यांकन डैशबोर्ड', chartLabel: 'विश्वसनीयता इतिहास चार्ट', chartTitle: 'लॉग किए गए प्रश्नों की विश्वसनीयता', observations: 'अवलोकन', chartEmpty: 'पहले विश्लेषण के बाद विश्वसनीयता इतिहास यहाँ दिखाई देगा।', queryStart: 'प्रश्न 01', queryLatest: 'नवीनतम प्रश्न', totalQueries: 'लॉग किए गए कुल प्रश्न', safeAbstention: 'सुरक्षित उत्तर-त्याग दर', averageConfidence: 'औसत विश्वसनीयता', answerAccuracy: 'उत्तर सटीकता', citationCorrectness: 'उद्धरण शुद्धता', classificationAccuracy: 'वर्गीकरण सटीकता', multilingualQuality: 'बहुभाषी उत्तर गुणवत्ता', pending: 'मूल्यांकन लंबित है', manualReviewSet: 'मूल्यांकन लंबित है — सत्यापित परीक्षण सेट के साथ मानव समीक्षा आवश्यक है', manualReview: 'मूल्यांकन लंबित है — मानव समीक्षा आवश्यक है', emptyTitle: 'आपका प्रमाण मार्ग यहाँ से शुरू होता है।', emptyBody: 'विश्वसनीयता इतिहास, उद्धरण जांच और वर्गीकरण समीक्षा भरने के लिए विश्लेषण चलाएँ।', citationReview: 'उद्धरण समीक्षा', note: 'मूल्यांकन लंबित है — अभी कोई प्रश्न लॉग नहीं हुआ है।' },
  },
  ta: {
    appName: 'சூத்ரதாரா',
    tagline: 'ஆயுர்வேதத்திற்கான AI-இயங்கும் IP மற்றும் ஒழுங்குமுறை அறிவாண்மை',
    team: 'டீம் சாதுர்யா',
    heroLede:
      'இந்த தளம் ஆயுர்வேத தயாரிப்புகளை பொருந்தக்கூடிய அறிவுசார் சொத்து அமைப்புகள், ஒழுங்குமுறை தேவைகள், அதிகார எல்லை சார்ந்த விதிகள் மற்றும் அதிகாரப்பூர்வ சான்றுகளுடன் இணைக்கிறது.',
    heroCta: 'ஒரு ஆயுர்வேத தயாரிப்பை பகுப்பாய்வு செய்யுங்கள்',

    navAnalyze: 'பகுப்பாய்வு',
    navAbs: 'ABS இணக்கம்',
    navTkdl: 'TKDL சரிபார்ப்பு',
    navEvidence: 'சான்றுகள்',
    navGraph: 'அறிவு வரைபடம்',
    navEval: 'மதிப்பீடு',

    inputLabel: 'உங்கள் ஆயுர்வேத தயாரிப்பு அல்லது IP கேள்வியை விவரிக்கவும்',
    placeholder: 'எ.கா. பாரம்பரிய நூலில் விவரிக்கப்பட்ட ஒரு பாரம்பரிய ஆயுர்வேத தயாரிப்புக்கு நான் காப்புரிமை பெற முடியுமா?',
    analyze: 'பகுப்பாய்வு செய்',
    analyzing: 'பகுப்பாய்வு செய்கிறது…',
    india: 'இந்தியா',
    international: 'சர்வதேசம்',
    disclaimer: 'தகவல் மட்டுமே, சட்ட ஆலோசனையல்ல.',
    classification: 'தயாரிப்பு வகைப்பாடு',
    jurisdiction: 'அதிகார எல்லை',
    applicableAreas: 'பொருந்தக்கூடிய IP மற்றும் ஒழுங்குமுறை பகுதிகள்',
    assessment: 'AI மதிப்பீடு',
    sources: 'சான்றுகள் மற்றும் மேற்கோள்கள்',
    confidence: 'சான்று நம்பிக்கை',
    escalate: 'IP வசதியாளருக்கு அனுப்பு',
    needExpert: 'நிபுணர் உதவி தேவையா?',
    detectedLanguage: 'கண்டறியப்பட்ட உள்ளீட்டு மொழி',
    retrievalNote: 'மீட்டெடுப்பிற்காக இயல்பாக்கப்பட்டது',
    evidenceBoundary: 'சான்று எல்லை',
    evidenceBoundaryBody: 'நம்பகமான பதிலை வழங்க போதுமான அதிகாரப்பூர்வ சான்றுகள் இல்லை.',
    whyAbstained: 'அமைப்பு ஏன் விலகியது',
    systemError: 'பகுப்பாய்வு சேவை தற்காலிகமாக கிடைக்கவில்லை. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',

    evidencePageTitle: 'சான்று உலாவி',
    evidencePageLede: 'கடைசி பதில் எங்கிருந்து வந்தது? கீழே உள்ள ஒவ்வொரு ஆதாரமும் உங்களின் சமீபத்திய பகுப்பாய்விற்காக அதிகாரப்பூர்வ தரவுத்தொகுப்பிலிருந்து பெறப்பட்டது.',
    evidenceEmpty: 'முதலில் ஒரு பகுப்பாய்வை இயலுங்கள் — மீட்டெடுக்கப்பட்ட ஆதாரங்கள் இங்கு தோன்றும்.',

    graphEmpty: 'பின்முனையிலிருந்து அறிவு வரைபடத் தரவு இப்போது கிடைக்கவில்லை.',
    evalEmpty: 'இந்த அமர்வில் இதுவரை எந்த கேள்விகளும் பதிவு செய்யப்படவில்லை.',

    absTitle: 'ABS இணக்கச் சரிபார்ப்பு',
    absLede: 'ஒரு கேள்வி பல்லுயிர் சட்டம், CBD மற்றும் நகோயா நெறிமுறையின் கீழ் அணுகல் மற்றும் பலன் பகிர்வு பொறுப்புகளைத் தூண்டுமா என்பதைச் சரிபார்க்கிறது.',
    absPlaceholder: 'எ.கா. இந்தியாவின் ஒரு குறிப்பிட்ட பகுதியிலிருந்து பெறப்பட்ட உயிரியல் வளத்தைப் பயன்படுத்தி தயாரிப்பை வணிகமயமாக்க விரும்புகிறோம்',
    absButton: 'ABS இணக்கத்தைச் சரிபார்',
    absEmpty: 'ABS சரிபார்ப்புப் பட்டியலைக் காண மேலே உள்ள தயாரிப்பு அல்லது ஆதாரச் சூழ்நிலையை விவரிக்கவும்.',
    absNotTriggered: 'இந்தக் கேள்விக்கு தெளிவான அணுகல் மற்றும் பலன் பகிர்வு சமிக்ஞை எதுவும் கிடைக்கவில்லை.',

    tkdlTitle: 'TKDL / முன் கலை சரிபார்ப்பு',
    tkdlLede: 'பாரம்பரிய தயாரிப்புக்கு பொருத்தமான பாரம்பரிய அறிவு டிஜிட்டல் நூலக பணிப்பாய்வை சுட்டிக்காட்டுகிறது.',
    tkdlPlaceholder: 'எ.கா. இந்த தயாரிப்பு ஏற்கனவே பாரம்பரிய நூலில் பாரம்பரிய அறிவாக ஆவணப்படுத்தப்பட்டுள்ளதா?',
    tkdlButton: 'TKDL / முன் கலையைச் சரிபார்',
    tkdlEmpty: 'பாரம்பரிய அறிவுச் சுட்டி மற்றும் தொடர்புடைய ஆதாரங்களைக் காண மேலே உள்ள தயாரிப்பை விவரிக்கவும்.',
    tkdlNotTriggered: 'இந்தக் கேள்விக்கு பாரம்பரிய அறிவுச் சுட்டி எதுவும் உருவாக்கப்படவில்லை.',

    languageEnglish: 'ஆங்கிலம்', languageTelugu: 'தெலுங்கு', languageHindi: 'இந்தி', languageTamil: 'தமிழ்', languageMalayalam: 'மலையாளம்', languageSanskrit: 'சமஸ்கிருதம்', primaryNavigation: 'முதன்மை வழிகாட்டல்', loadingAnalysis: 'பகுப்பாய்வு ஏற்றப்படுகிறது',
    analysisHelper: 'தேர்ந்தெடுக்கப்பட்ட அதிகார எல்லையில் சான்று அடிப்படையிலான பகுப்பாய்வு', jurisdictionPrefix: 'அதிகார எல்லை',
    clarificationCategories: ['பாரம்பரிய / பொதுவான மருந்து', 'காப்புரிமை / தனியுரிம மருந்து', 'புதிய / பாரம்பரியமற்ற மருந்து', 'பைட்டோஃபார்மாசூட்டிகல்', 'ஆயுர்வேத-ஆஹார் / நியூட்ராசூட்டிகல்', 'சாதனம் / அழகுசாதனம்'],
    paraphraseVerified: 'Groq மூலம் விவரிக்கப்பட்டது · மேற்கோள்கள் சரிபார்க்கப்பட்டன', translationUnavailableAnswer: 'மொழிபெயர்ப்பு சேவை இப்போது கிடைக்கவில்லை — ஆங்கிலப் பதில் காட்டப்படுகிறது.',
    tkPointer: 'பாரம்பரிய அறிவு / முன் கலை சுட்டி', absConsiderations: 'சாத்தியமான ABS பரிசீலனைகள்',
    absChecklist: { biologicalResource: 'உயிரியல் வளம் உட்பட்டது', provenance: 'ஆதாரம் / தோற்றம் கண்டறியப்பட்டது', framework: 'தொடர்புடைய ABS கட்டமைப்பு கண்டறியப்பட்டது', source: 'ஆதார ஆதாரம் மீட்டெடுக்கப்பட்டது' },
    confidenceSupport: 'சமீபத்திய ஆதாரங்கள் இந்த பகுப்பாய்வை எவ்வளவு வலுவாக ஆதரிக்கின்றன', compositeConfidence: 'கூட்டு நம்பிக்கை', confidenceScale: 'நம்பிக்கை அளவுகோல்',
    confidenceFactors: { retrieval_relevance: 'மீட்டெடுப்பு பொருத்தம்', source_count_factor: 'ஆதார எண்ணிக்கை', source_authority: 'ஆதார அதிகாரம்', agreement: 'டொமைன் ஒப்பந்தம்', classification_confidence: 'வகைப்பாட்டு நம்பிக்கை' },
    confidenceNote: 'இந்த பகுப்பாய்வால் உண்மையில் உருவாக்கப்பட்ட மீட்டெடுப்பு மற்றும் வகைப்பாட்டு சமிக்ஞைகளிலிருந்து கணக்கிடப்பட்ட கூட்டு மதிப்பெண்.',
    translationUnavailableMessage: 'மொழிபெயர்ப்பு சேவை இப்போது கிடைக்கவில்லை — ஆங்கில செய்தி காட்டப்படுகிறது.', evidenceBoundaryReason: 'சேகரிக்கப்பட்ட சான்றுகளின் தொகுதி காலியாக உள்ளது அல்லது அதன் ஒருங்கிணைந்த நம்பிக்கை பாதுகாப்பு வரம்பிற்குக் கீழே உள்ளது.',
    sourceLabel: 'ஆதாரம்', matchLabel: 'பொருத்தம்', sourceFields: { authority: 'அதிகாரம்', domain: 'டொமைன்', type: 'ஆதார வகை', version: 'பதிப்பு', retrieved: 'மீட்டெடுக்கப்பட்டது', precision: 'துல்லியம்' }, viewSource: 'ஆதாரத்தைப் பார்',
    builtFor: 'ஆயுஷ் அமைச்சகம் மற்றும் அகில இந்திய ஆயுர்வேத நிறுவனத்திற்காக உருவாக்கப்பட்டது', liveEvidenceTrail: 'ஒரு நேரடி சான்றுப் பாதை', heroTraceTitle: 'தயாரிப்பிலிருந்து விதிமுறை வரை, சங்கிலி புலப்படுகிறது.', heroTraceBody: 'SUTRADHARA கேள்வியை வகைப்படுத்துகிறது, பொருத்தமான அமைப்பிற்கு வழிநடத்துகிறது மற்றும் ஆதாரத்தைப் பார்வையில் வைக்கிறது.', citationGrounded: 'மேற்கோள் அடிப்படையில் அமைந்தது',
    heroTrace: [{ label: 'தயாரிப்பு கேள்வி', value: 'நாவல் செயல்முறையுடன் அஸ்வகந்தா சாறு' }, { label: 'வகைப்பாடு', value: 'பைட்டோஃபார்மாசூட்டிகல் / உயிரியல் வளம்' }, { label: 'சான்று பாதை', value: 'பல்லுயிர் சட்டம், 2002 · பிரிவு 7' }], sourceRetained: 'ஆதாரம் தக்கவைக்கப்பட்டது', confidenceHigh: 'நம்பிக்கை: உயர்',
    focusedTool: 'செறிவூட்டப்பட்ட ஆராய்ச்சி கருவி', working: 'வேலை செய்கிறது…', absChecklistLabel: 'ABS சரிபார்ப்புப் பட்டியல்', tkdlPointerLabel: 'TKDL சுட்டி', preview: 'முன்னோட்டம்',
    reviewPathway: 'மனித மறுஆய்வு பாதை', escalateTitle: 'IP வசதியாளருக்கு அனுப்பு', escalationDescription: 'ஒரு மனித வசதியாளர் கீழே மீட்டெடுக்கப்பட்ட சான்றுகளுடன் இந்தக் கேள்வியை மதிப்பாய்வு செய்வார்.', escalationRecorded: 'எஸ்கலேஷன் பதிவு செய்யப்பட்டது.', escalationFollowUp: 'ஒரு வசதியாளர் கீழே உள்ள சூழலைப் பயன்படுத்தி தொடர்புகொள்வார்.',
    escalationFields: { query: 'கேள்வி', category: 'வகை', jurisdiction: 'அதிகார எல்லை', areas: 'பகுதிகள்', sources: 'ஆதாரங்கள்' }, noSources: 'எதுவுமில்லை', contactEmail: 'தொடர்பு மின்னஞ்சல் (விருப்பமானது)', emailPlaceholder: 'you@example.com', escalationError: 'எஸ்கலேஷன் சேவையை அடைய முடியவில்லை — மீண்டும் முயற்சிக்கவும்.', cancel: 'ரத்து செய்', sending: 'அனுப்புகிறது…', submit: 'சமர்ப்பி',
    graphGrounding: 'பதில் எவ்வாறு ஆதாரப்படுத்தப்பட்டுள்ளது', explainabilityGraph: 'விளக்க வரைபடம்', graphLegend: { query: 'கேள்வி சூழல்', regulatory: 'ஒழுங்குமுறை அமைப்பு', traditional: 'பாரம்பரிய அறிவு', authoritative: 'அதிகாரப்பூர்வ ஆதாரம்' },
    classificationCategories: { 'Classical / Generic Medicine': 'பாரம்பரிய / பொதுவான மருந்து', 'Patent / Proprietary Medicine': 'காப்புரிமை / தனியுரிம மருந்து', 'New / Non-Classical Drug': 'புதிய / பாரம்பரியமற்ற மருந்து', Phytopharmaceutical: 'பைட்டோஃபார்மாசூட்டிகல்', 'Ayurveda-Aahar / Nutraceutical': 'ஆயுர்வேத-ஆஹார் / நியூட்ராசூட்டிகல்', Cosmetic: 'அழகுசாதனம்' }, areaLabels: { Patents: 'காப்புரிமைகள்', 'Geographical Indications': 'புவிசார் குறியீடுகள்', Trademarks: 'வர்த்தக முத்திரைகள்', Copyright: 'பதிப்புரிமை', Designs: 'வடிவமைப்புகள்', 'Trade Secrets': 'வர்த்தக ரகசியங்கள்', 'Plant Variety Protection': 'தாவர வகை பாதுகாப்பு', 'Traditional Knowledge': 'பாரம்பரிய அறிவு', 'Access-and-Benefit-Sharing': 'அணுகல் மற்றும் பலன் பகிர்வு', 'Drug regulation': 'மருந்து ஒழுங்குமுறை', Advertising: 'விளம்பரம்', Labelling: 'லேபிளிங்', 'Food / nutraceutical regulation': 'உணவு / நியூட்ராசூட்டிகல் ஒழுங்குமுறை', 'Cosmetic regulation': 'அழகுசாதன ஒழுங்குமுறை' },
    graphNodes: { product: 'ஆயுர்வேத தயாரிப்பு', category: 'தயாரிப்பு வகை', tk: 'பாரம்பரிய அறிவு', regime: 'IP / ஒழுங்குமுறை அமைப்பு', law: 'ஆளும் சட்டம்', provision: 'விதிமுறை', source: 'அதிகாரப்பூர்வ ஆதாரம்' }, graphEdges: { product_category: 'சார்ந்தது', category_regime: 'தொடர்புடையது', category_tk: 'குறிப்பிடலாம்', regime_law: 'சட்டத்தால் ஆளப்படுகிறது', law_provision: 'கொண்டுள்ளது', provision_source: 'ஆதாரத்தால் ஆதரிக்கப்படுகிறது' },
    eval: { observability: 'அமைப்பு அவதானிப்பு', title: 'மதிப்பீட்டு டாஷ்போர்டு', chartLabel: 'நம்பிக்கை வரலாற்று வரைபடம்', chartTitle: 'பதிவு செய்யப்பட்ட கேள்விகளின் நம்பிக்கை', observations: 'அவதானிப்புகள்', chartEmpty: 'முதல் பகுப்பாய்விற்குப் பிறகு நம்பிக்கை வரலாறு இங்கு தோன்றும்.', queryStart: 'கேள்வி 01', queryLatest: 'சமீபத்திய கேள்வி', totalQueries: 'பதிவு செய்யப்பட்ட மொத்த கேள்விகள்', safeAbstention: 'பாதுகாப்பான விலகல் விகிதம்', averageConfidence: 'சராசரி நம்பிக்கை', answerAccuracy: 'பதில் துல்லியம்', citationCorrectness: 'மேற்கோள் சரிபார்ப்பு', classificationAccuracy: 'வகைப்பாட்டு துல்லியம்', multilingualQuality: 'பல்மொழி பதில் தரம்', pending: 'மதிப்பீடு நிலுவையில் உள்ளது', manualReviewSet: 'மதிப்பீடு நிலுவையில் உள்ளது — மனித மறுஆய்வு தேவை', manualReview: 'மதிப்பீடு நிலுவையில் உள்ளது', emptyTitle: 'உங்கள் சான்றுப் பாதை இங்கு தொடங்குகிறது.', emptyBody: 'நம்பிக்கை வரலாறு மற்றும் வகைப்பாட்டு மதிப்பாய்வை நிரப்ப பகுப்பாய்வை இயக்கவும்.', citationReview: 'மேற்கோள் மதிப்பாய்வு', note: 'மதிப்பீடு நிலுவையில் உள்ளது — இதுவரை கேள்விகள் பதிவு செய்யப்படவில்லை.' },
  },
  ml: {
    appName: 'സൂത്രധാര',
    tagline: 'ആയുർവേദത്തിനായുള്ള AI-അധിഷ്ഠിത IP & റെഗുലേറ്ററി ഇന്റലിജൻസ്',
    team: 'ടീം ചാതുര്യ',
    heroLede:
      'ഈ പ്ലാറ്റ്‌ഫോം ആയുർവേദ ഉൽപ്പന്നങ്ങളെ ബാധകമായ ബൗദ്ധിക സ്വത്തവകാശ സംവിധാനങ്ങൾ, റെഗുലേറ്ററി ആവശ്യകതകൾ, അധികാരപരിധി-നിർദ്ദിഷ്ട നിയമങ്ങൾ, ഔദ്യോഗിക തെളിവുകൾ എന്നിവയുമായി ബന്ധിപ്പിക്കുന്നു.',
    heroCta: 'ഒരു ആയുർവേദ ഉൽപ്പന്നം വിശകലനം ചെയ്യുക',

    navAnalyze: 'വിശകലനം',
    navAbs: 'ABS അനുസരണം',
    navTkdl: 'TKDL പരിശോധന',
    navEvidence: 'തെളിവുകൾ',
    navGraph: 'നോളജ് ഗ്രാഫ്',
    navEval: 'മൂല്യനിർണ്ണയം',

    inputLabel: 'നിങ്ങളുടെ ആയുർവേദ ഉൽപ്പന്നം അല്ലെങ്കിൽ IP ചോദ്യം വിവരിക്കുക',
    placeholder: 'ഉദാ. ഒരു പരമ്പരാഗത ഗ്രന്ഥത്തിൽ വിവരിച്ചിട്ടുള്ള ശാസ്ത്രീയ ആയുർവേദ ഫോർമുലേഷന് എനിക്ക് പേറ്റന്റ് ലഭിക്കുമോ?',
    analyze: 'വിശകലനം ചെയ്യുക',
    analyzing: 'വിശകലനം ചെയ്യുന്നു…',
    india: 'ഇന്ത്യ',
    international: 'അന്താരാഷ്ട്രം',
    disclaimer: 'വിവരങ്ങൾ മാത്രം, നിയമോപദേശമല്ല.',
    classification: 'ഉൽപ്പന്ന വർഗ്ഗീകരണം',
    jurisdiction: 'അധികാരപരിധി',
    applicableAreas: 'ബാധകമായ IP & റെഗുലേറ്ററി മേഖലകൾ',
    assessment: 'AI വിലയിരുത്തൽ',
    sources: 'തെളിവുകളും ഉദ്ധരണികളും',
    confidence: 'തെളിവ് വിശ്വസനീയത',
    escalate: 'IP ഫെസിലിറ്റേറ്റർക്ക് അയക്കുക',
    needExpert: 'വിദഗ്ദ്ധ സഹായം വേണോ?',
    detectedLanguage: 'കണ്ടെത്തിയ ഇൻപുട്ട് ഭാഷ',
    retrievalNote: 'റെട്രീവലിനായി സാധാരണ നിലയിലാക്കി',
    evidenceBoundary: 'തെളിവ് പരിധി',
    evidenceBoundaryBody: 'വിശ്വസനീയമായ ഉത്തരം നൽകാൻ ആവശ്യമായ ഔദ്യോഗിക തെളിവുകൾ ലഭ്യമല്ല.',
    whyAbstained: 'സിസ്റ്റം എന്തുകൊണ്ട് ഉത്തരം നൽകിയില്ല',
    systemError: 'വിശകലന സേവനം താൽക്കാലികമായി ലഭ്യമല്ല. ദയവായി കുറച്ച് കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കുക.',

    evidencePageTitle: 'തെളിവ് എക്സ്പ്ലോറർ',
    evidencePageLede: 'അവസാന ഉത്തരം എവിടെ നിന്നാണ് വന്നത്? താഴെ നൽകിയിരിക്കുന്ന ഓരോ ഉറവിടവും നിങ്ങളുടെ സമീപകാല വിശകലനത്തിനായി ഔദ്യോഗിക കോർപ്പസിൽ നിന്ന് ശേഖരിച്ചതാണ്.',
    evidenceEmpty: 'ആദ്യം ഒരു വിശകലനം നടത്തുക — ശേഖരിച്ച ഉറവിടങ്ങൾ ഇവിടെ കാണാം.',

    graphEmpty: 'ബാക്കെൻഡിൽ നിന്ന് നോളജ് ഗ്രാഫ് ഡാറ്റ നിലവിൽ ലഭ്യമല്ല.',
    evalEmpty: 'ഈ സെഷനിൽ ഇതുവരെ ചോദ്യങ്ങളൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.',

    absTitle: 'ABS അനുസരണ പരിശോധന',
    absLede: 'ജൈവവൈവിധ്യ നിയമം, CBD, നഗോയ പ്രോട്ടോക്കോൾ എന്നിവയ്ക്ക് കീഴിൽ ഒരു ചോദ്യം ആക്സസ്-ആൻഡ്-ബെനിഫിറ്റ്-ഷെയറിംഗ് ബാധ്യതകൾ വരുത്തുമോ എന്ന് പരിശോധിക്കുന്നു.',
    absPlaceholder: 'ഉദാ. ഇന്ത്യയിലെ ഒരു പ്രത്യേക പ്രദേശത്ത് നിന്ന് ശേഖരിച്ച ജൈവ വിഭവം ഉപയോഗിച്ച് ഫോർമുലേഷൻ വാണിജ്യവൽക്കരിക്കാൻ ഞങ്ങൾ ആഗ്രഹിക്കുന്നു',
    absButton: 'ABS അനുസരണം പരിശോധിക്കുക',
    absEmpty: 'ABS ചെക്ക്‌ലിസ്റ്റ് കാണുന്നതിന് മുകളിൽ ഉൽപ്പന്നം അല്ലെങ്കിൽ ഉറവിട സാഹചര്യം വിവരിക്കുക.',
    absNotTriggered: 'ഈ ചോദ്യത്തിന് വ്യക്തമായ ആക്സസ്-ആൻഡ്-ബെനിഫിറ്റ്-ഷെയറിംഗ് സൂചനയൊന്നും ലഭിച്ചില്ല.',

    tkdlTitle: 'TKDL / മുൻകാല വിവര പരിശോധന',
    tkdlLede: 'ഒരു ശാസ്ത്രീയ ഫോർമുലേഷന് പ്രസക്തമായ ട്രഡിഷണൽ നോളജ് ഡിജിറ്റൽ ലൈബ്രറി വർക്ക്ഫ്ലോ ചൂണ്ടിക്കാണിക്കുന്നു.',
    tkdlPlaceholder: 'ഉദാ. ഈ ഫോർമുലേഷൻ ഒരു പരമ്പരാഗത ഗ്രന്ഥത്തിൽ പാരമ്പര്യ അറിവായി രേഖപ്പെടുത്തിയിട്ടുണ്ടോ?',
    tkdlButton: 'TKDL / മുൻകാല വിവരങ്ങൾ പരിശോധിക്കുക',
    tkdlEmpty: 'പാരമ്പര്യ അറിവ് സൂചികയും ബന്ധപ്പെട്ട ഉറവിടങ്ങളും കാണുന്നതിന് മുകളിൽ ഫോർമുലേഷൻ വിവരിക്കുക.',
    tkdlNotTriggered: 'ഈ ചോദ്യത്തിന് പാരമ്പര്യ അറിവ് സൂചിക നിർമ്മിച്ചിട്ടില്ല.',

    languageEnglish: 'ഇംഗ്ലീഷ്', languageTelugu: 'തെലുങ്ക്', languageHindi: 'ഹിന്ദി', languageTamil: 'തമിഴ്', languageMalayalam: 'മലയാളം', languageSanskrit: 'സംസ്കൃതം', primaryNavigation: 'പ്രധാന നാവിഗേഷൻ', loadingAnalysis: 'വിശകലനം ലോഡ് ചെയ്യുന്നു',
    analysisHelper: 'തിരഞ്ഞെടുത്ത അധികാരപരിധിയിൽ തെളിവുകൾ അടിസ്ഥാനമാക്കിയുള്ള വിശകലനം', jurisdictionPrefix: 'അധികാരപരിധി',
    clarificationCategories: ['ശാസ്ത്രീയ / ജനറിക് മരുന്ന്', 'പേറ്റന്റ് / പ്രൊപ്രൈറ്ററി മരുന്ന്', 'പുതിയ / ശാസ്ത്രീയമല്ലാത്ത മരുന്ന്', 'ഫൈറ്റോഫാർമസ്യൂട്ടിക്കൽ', 'ആയൂർവേദ-ആഹാർ / ന്യൂട്രാസ്യൂട്ടിക്കൽ', 'കോസ്മെറ്റിക്'],
    paraphraseVerified: 'Groq വഴി രൂപപ്പെടുത്തിയത് · ഉദ്ധരണികൾ ശരിയാണെന്ന് സ്ഥിരീകരിച്ചു', translationUnavailableAnswer: 'തർജ്ജമ സേവനം നിലവിൽ ലഭ്യമല്ല — ഇംഗ്ലീഷ് ഉത്തരം കാണിക്കുന്നു.',
    tkPointer: 'പാരമ്പര്യ അറിവ് / മുൻകാല വിവര സൂചിക', absConsiderations: 'സാധ്യമായ ABS പരിഗണനകൾ',
    absChecklist: { biologicalResource: 'ജൈവ വിഭവം ഉൾപ്പെട്ടിരിക്കുന്നു', provenance: 'ഉറവിടം / ഉത്ഭവം കണ്ടെത്തി', framework: 'പ്രസക്തമായ ABS ചട്ടക്കൂട് കണ്ടെത്തി', source: 'പിന്തുണയ്ക്കുന്ന ഉറവിടം ലഭിച്ചു' },
    confidenceSupport: 'ലഭ്യമായ ഉറവിടങ്ങൾ ഈ വിശകലനത്തെ എത്രത്തോളം ശക്തമായി പിന്തുണയ്ക്കുന്നു', compositeConfidence: 'സമ്മിശ്ര വിശ്വസനീയത', confidenceScale: 'വിശ്വസനീയത അളവ്',
    confidenceFactors: { retrieval_relevance: 'റെട്രീവൽ പ്രസക്തി', source_count_factor: 'ഉറവിടങ്ങളുടെ എണ്ണം', source_authority: 'ഉറവിട അധികാരം', agreement: 'ഡൊമെയ്ൻ സമ്മതി', classification_confidence: 'വർഗ്ഗീകരണ വിശ്വസനീയത' },
    confidenceNote: 'ഈ വിശകലനത്തിൽ നിന്ന് യഥാർത്ഥത്തിൽ ലഭിച്ച സിഗ്നലുകളിൽ നിന്ന് കണക്കാക്കിയ സമ്മിശ്ര സ്കോർ.',
    translationUnavailableMessage: 'തർജ്ജമ സേവനം നിലവിൽ ലഭ്യമല്ല — ഇംഗ്ലീഷ് സന്ദേശം കാണിക്കുന്നു.', evidenceBoundaryReason: 'ശേഖരിച്ച തെളിവുകളുടെ സെറ്റ് ശൂന്യമാണ് അല്ലെങ്കിൽ അതിന്റെ സമ്മിശ്ര വിശ്വസനീയത സുരക്ഷിത പരിധിക്ക് താഴെയാണ്.',
    sourceLabel: 'ഉറവിടം', matchLabel: 'പൊരുത്തം', sourceFields: { authority: 'അധികാരം', domain: 'ഡൊമെയ്ൻ', type: 'ഉറവിട തരം', version: 'പതിപ്പ്', retrieved: 'ശേഖരിച്ച തീയതി', precision: 'കൃത്യത' }, viewSource: 'ഉറവിടം കാണുക',
    builtFor: 'ആയൂഷ് മന്ത്രാലയത്തിനും ഓൾ ഇന്ത്യ ഇൻസ്റ്റിറ്റ്യൂട്ട് ഓഫ് ആയുർവേദയ്ക്കുമായി നിർമ്മിച്ചത്', liveEvidenceTrail: 'ഒരു തത്സമയ തെളിവ് വഴി', heroTraceTitle: 'ഉൽപ്പന്നത്തിൽ നിന്ന് നിയമവ്യവസ്ഥയിലേക്ക്, വഴി വ്യക്തമാണ്.', heroTraceBody: 'SUTRADHARA ചോദ്യത്തെ വർഗ്ഗീകരിക്കുകയും ബന്ധപ്പെട്ട മേഖലയിലേക്ക് നയിക്കുകയും ഉറവിടം വ്യക്തമാക്കുകയും ചെയ്യുന്നു.', citationGrounded: 'ഉദ്ധരണി അധിഷ്ഠിതം',
    heroTrace: [{ label: 'ഉൽപ്പന്ന ചോദ്യം', value: 'പുതിയ പ്രക്രിയയുള്ള അശ്വഗന്ധ എക്സ്ട്രാക്റ്റ്' }, { label: 'വർഗ്ഗീകരണം', value: 'ഫൈറ്റോഫാർമസ്യൂട്ടിക്കൽ / ജൈവ വിഭവം' }, { label: 'തെളിവ് വഴി', value: 'ജൈവവൈവിധ്യ നിയമം, 2002 · സെക്ഷൻ 7' }], sourceRetained: 'ഉറവിടം നിലനിർത്തി', confidenceHigh: 'വിശ്വസനീയത: ഉയർന്നത്',
    focusedTool: 'കേന്ദ്രീകൃത ഗവേഷണ ഉപകരണം', working: 'പ്രവർത്തിക്കുന്നു…', absChecklistLabel: 'ABS ചെക്ക്‌ലിസ്റ്റ്', tkdlPointerLabel: 'TKDL സൂചിക', preview: 'പ്രദർശനം',
    reviewPathway: 'മനുഷ്യ പരിശോധന വഴി', escalateTitle: 'IP ഫെസിലിറ്റേറ്റർക്ക് അയക്കുക', escalationDescription: 'ഒരു വിദഗ്ദ്ധൻ താഴെ നൽകിയിട്ടുള്ള തെളിവുകൾക്കൊപ്പം ഈ ചോദ്യം പരിശോധിക്കും.', escalationRecorded: 'എസ്‌കലേഷൻ രേഖപ്പെടുത്തി.', escalationFollowUp: 'ഒരു ഫെസിലിറ്റേറ്റർ നിങ്ങളെ ബന്ധപ്പെടും.',
    escalationFields: { query: 'ചോദ്യം', category: 'വിഭാഗം', jurisdiction: 'അധികാരപരിധി', areas: 'മേഖലകൾ', sources: 'ഉറവിടങ്ങൾ' }, noSources: 'ഒന്നുമില്ല', contactEmail: 'ഇമെയിൽ (ഐച്ഛികം)', emailPlaceholder: 'you@example.com', escalationError: 'എസ്‌കലേഷൻ സേവനത്തിൽ ബന്ധപ്പെടാൻ കഴിഞ്ഞില്ല — വീണ്ടും ശ്രമിക്കുക.', cancel: 'റദ്ദാക്കുക', sending: 'അയക്കുന്നു…', submit: 'സമർപ്പിക്കുക',
    graphGrounding: 'ഉത്തരം എങ്ങനെ തെളിയിക്കപ്പെട്ടിരിക്കുന്നു', explainabilityGraph: 'വിശദീകരണ ഗ്രാഫ്', graphLegend: { query: 'ചോദ്യ പശ്ചാത്തലം', regulatory: 'റെഗുലേറ്ററി ഘടന', traditional: 'പരമ്പരാഗത അറിവ്', authoritative: 'ഔദ്യോഗിക ഉറവിടം' },
    classificationCategories: { 'Classical / Generic Medicine': 'ശാസ്ത്രീയ / ജനറിക് മരുന്ന്', 'Patent / Proprietary Medicine': 'പേറ്റന്റ് / പ്രൊപ്രൈറ്ററി മരുന്ന്', 'New / Non-Classical Drug': 'പുതിയ / ശാസ്ത്രീയമല്ലാത്ത മരുന്ന്', Phytopharmaceutical: 'ഫൈറ്റോഫാർമസ്യൂട്ടിക്കൽ', 'Ayurveda-Aahar / Nutraceutical': 'ആയൂർവേദ-ആഹാർ / ന്യൂട്രാസ്യൂട്ടിക്കൽ', Cosmetic: 'കോസ്മെറ്റിക്' }, areaLabels: { Patents: 'പേറ്റന്റുകൾ', 'Geographical Indications': 'ഭൂമിശാസ്ത്രപരമായ സൂചകങ്ങൾ', Trademarks: 'ട്രേഡ്മാർക്കുകൾ', Copyright: 'കോപ്പിറൈറ്റ്', Designs: 'ഡിസൈനുകൾ', 'Trade Secrets': 'വ്യാപാര രഹസ്യങ്ങൾ', 'Plant Variety Protection': 'സസ്യ വൈവിധ്യ സംരക്ഷണം', 'Traditional Knowledge': 'പാരമ്പര്യ അറിവ്', 'Access-and-Benefit-Sharing': 'ആക്സസ്-ആൻഡ്-ബെനിഫിറ്റ്-ഷെയറിംഗ്', 'Drug regulation': 'മരുന്ന് നിയന്ത്രണം', Advertising: 'പരസ്യം', Labelling: 'ലേബലിംഗ്', 'Food / nutraceutical regulation': 'ഭക്ഷണ / ന്യൂട്രാസ്യൂട്ടിക്കൽ നിയന്ത്രണം', 'Cosmetic regulation': 'കോസ്മെറ്റിക് നിയന്ത്രണം' },
    graphNodes: { product: 'ആയുർവേദ ഉൽപ്പന്നം', category: 'ഉൽപ്പന്ന വിഭാഗം', tk: 'പാരമ്പര്യ അറിവ്', regime: 'IP / റെഗുലേറ്ററി സംവിധാനം', law: 'നിയമം', provision: 'വകുപ്പ്', source: 'ഔദ്യോഗിക ഉറവിടം' }, graphEdges: { product_category: 'ഭാഗമാണ്', category_regime: 'ബന്ധപ്പെട്ടിരിക്കുന്നു', category_tk: 'സൂചിപ്പിക്കാം', regime_law: 'നിയമത്താൽ നിയന്ത്രിക്കപ്പെടുന്നു', law_provision: 'ഉൾക്കൊള്ളുന്നു', provision_source: 'ഉറവിടത്താൽ പിന്തുണയ്ക്കുന്നു' },
    eval: { observability: 'സിസ്റ്റം നിരീക്ഷണം', title: 'മൂല്യനിർണ്ണയ ഡാഷ്‌ബോർഡ്', chartLabel: 'വിശ്വസനീയത ചരിത്ര ചാർട്ട്', chartTitle: 'രേഖപ്പെടുത്തിയ ചോദ്യങ്ങളുടെ വിശ്വസനീയത', observations: 'നിരീക്ഷണങ്ങൾ', chartEmpty: 'ആദ്യ വിശകലനത്തിന് ശേഷം വിശ്വസനീയത ചരിത്രം ഇവിടെ കാണാം.', queryStart: 'ചോദ്യം 01', queryLatest: 'അവസാന ചോദ്യം', totalQueries: 'ആകെ രേഖപ്പെടുത്തിയ ചോദ്യങ്ങൾ', safeAbstention: 'സുരക്ഷിത ഉത്തരം-ഒഴിവാക്കൽ നിരക്ക്', averageConfidence: 'ശരാശരി വിശ്വസനീയത', answerAccuracy: 'ഉത്തര കൃത്യത', citationCorrectness: 'ഉദ്ധരണി കൃത്യത', classificationAccuracy: 'വർഗ്ഗീകരണ കൃത്യത', multilingualQuality: 'ബഹുഭാഷാ ഉത്തര ഗുണമേന്മ', pending: 'മൂല്യനിർണ്ണയം ബാക്കിയാണ്', manualReviewSet: 'മൂല്യനിർണ്ണയം ബാക്കിയാണ് — മാനുവൽ പരിശോധന ആവശ്യമാണ്', manualReview: 'മൂല്യനിർണ്ണയം ബാക്കിയാണ്', emptyTitle: 'നിങ്ങളുടെ തെളിവ് വഴി ഇവിടെ ആരംഭിക്കുന്നു.', emptyBody: 'വിശകലനം നടത്തുക.', citationReview: 'ഉദ്ധരണി പരിശോധന', note: 'മൂല്യനിർണ്ണയം ബാക്കിയാണ്.' },
  },
  sa: {
    appName: 'सूत्रधारः',
    tagline: 'आयुर्वेदस्य कृते AI-सञ्चालिता बौद्धिक-सम्पदा नियमन-प्रज्ञा',
    team: 'चातुर्य-दलम्',
    heroLede:
      'इदं मञ्चम् आयुर्वेदिक-उत्पादानि सम्बद्धैः बौद्धिक-सम्पदा-विधानैः, नियामक-आवश्यकताभिः, क्षेत्राधिकार-नियमैः प्रमाणैश्च योजयति।',
    heroCta: 'आयुर्वेदिक-उत्पादस्य विश्लेषणं करोतु',

    navAnalyze: 'विश्लेषणम्',
    navAbs: 'ABS अनुपालनम्',
    navTkdl: 'TKDL परीक्षणम्',
    navEvidence: 'प्रमाणानि',
    navGraph: 'ज्ञान-आलेखः',
    navEval: 'मूल्याङ्कनम्',

    inputLabel: 'स्वस्य आयुर्वेदिक-उत्पादस्य अथवा IP-प्रश्नस्य वर्णनं करोतु',
    placeholder: 'यथा शास्त्रेषु वर्णितस्य शास्त्रीय-आयुर्वेदिक-उत्पादस्य पेटेण्ट् प्राप्तुं शक्यते किम्?',
    analyze: 'विश्लेषणं करोतु',
    analyzing: 'विश्लेषणं भवति…',
    india: 'भारतम्',
    international: 'अन्तर्राष्ट्रियम्',
    disclaimer: 'सूचनामात्रम्, न तु विधि-परामर्शः।',
    classification: 'उत्पाद-वर्गीकरणम्',
    jurisdiction: 'क्षेत्राधिकारः',
    applicableAreas: 'सम्बद्धानि IP-क्षेत्राणि',
    assessment: 'AI मूल्यनिर्णयः',
    sources: 'प्रमाणानि उद्धरणानि च',
    confidence: 'प्रमाण-विश्वसनीयता',
    escalate: 'IP-सुविधादात्रे प्रेषयतु',
    needExpert: 'विशेषज्ञ-सहायता आवश्यकी किम्?',
    detectedLanguage: 'अभिज्ञाता इनपुट-भाषा',
    retrievalNote: 'पुनःप्राप्तये सामान्यीकृतम्',
    evidenceBoundary: 'प्रमाण-सीमा',
    evidenceBoundaryBody: 'विश्वसनीय-उत्तराय पर्याप्तं आधिकारिक-प्रमाणं न उपलब्धम्।',
    whyAbstained: 'प्रणाल्या उत्तरं किमर्थं न दत्तम्',
    systemError: 'विश्लेषण-सेवा तात्कालिकरूपेण न उपलभ्यते।',

    evidencePageTitle: 'प्रमाण-अन्वेषकः',
    evidencePageLede: 'अन्तिमम् उत्तरं कुतः आगतम्? अधो लिखितः प्रत्येकः स्रोतः आधिकारिक-कोषात् प्राप्तः।',
    evidenceEmpty: 'प्रथमं विश्लेषणं करोतु — प्राप्ताः स्रोताः अत्र दृश्यन्ते।',

    graphEmpty: 'ज्ञान-आलेख-दत्तांशः अधुना न उपलब्धः।',
    evalEmpty: 'अस्मिन सत्रे अद्यापि कोऽपि प्रश्नः न पञ्जीकृतः।',

    absTitle: 'ABS अनुपालन-परीक्षणम्',
    absLede: 'जैविविधता-अधिनियम-नागोया-प्रोटोकॉल-अन्तर्गतं ABS दायित्वं भवति वा इति परीक्षते।',
    absPlaceholder: 'यथा भारतस्य कस्माच्चित् प्रदेशात् प्राप्तस्य जैविक-संसाधनस्य उपयोगेन उत्पादस्य व्यवसायीकरणम्',
    absButton: 'ABS अनुपालनं परीक्षताम्',
    absEmpty: 'ABS पञ्जीं द्रष्टुम् उपरि उत्पादस्य वर्णनं करोतु।',
    absNotTriggered: 'अस्य प्रश्नस्य कृते स्पष्टः ABS संकेत न प्राप्तः।',

    tkdlTitle: 'TKDL / पूर्व-ज्ञान-परीक्षणम्',
    tkdlLede: 'शास्त्रीय-उत्पादस्य कृते पारंपरिक-ज्ञान-डिजिटल-पुस्तकालय-प्रक्रियां दर्शयति।',
    tkdlPlaceholder: 'यथा किम् अयं योगः शास्त्रीय-ग्रन्थे पारंपरिक-ज्ञानरूपेण वर्णितः अस्ति?',
    tkdlButton: 'TKDL / पूर्व-ज्ञानं परीक्षताम्',
    tkdlEmpty: 'पारंपरिक-ज्ञान-संकेतं द्रष्टुम् उपरि योगस्य वर्णनं करोतु।',
    tkdlNotTriggered: 'अस्य प्रश्नस्य कृते पारंपरिक-ज्ञान-संकेतः न निर्मितः।',

    languageEnglish: 'आङ्गलभाषा', languageTelugu: 'तेलुगुभाषा', languageHindi: 'हिन्दी', languageTamil: 'तमिळ्', languageMalayalam: 'मलय़ाळम्', languageSanskrit: 'संस्कृतम्', primaryNavigation: 'मुख्य-सञ्चरणम्', loadingAnalysis: 'विश्लेषणं लोड भवति',
    analysisHelper: 'चयनित-क्षेत्राधिकार-अन्तर्गतं प्रमाण-आधारित-विश्लेषणम्', jurisdictionPrefix: 'क्षेत्राधिकारः',
    clarificationCategories: ['शास्त्रीय / सामान्य औषधम्', 'पेटेण्ट् / स्वामित्वायुत औषधम्', 'नवीन / अशास्त्रीय औषधम्', 'फाइटोफार्मास्यूटिकल', 'आयुर्वेद-आहारः / न्यूट्रास्यूटिकल', 'सौंदर्यवर्धकम्'],
    paraphraseVerified: 'Groq द्वारा रूपान्तरितम् · उद्धरणानि सत्यापितानि', translationUnavailableAnswer: 'अनुवाद-सेवा अधुना न उपलभ्यते — आङ्गलभाषा-उत्तरं दृश्यते।',
    tkPointer: 'पारंपरिक-ज्ञान / पूर्व-कला संकेतह्', absConsiderations: 'संभाव्याः ABS विचारणाः',
    absChecklist: { biologicalResource: 'जैविक-संसाधनं सम्मिलितम्', provenance: 'उत्पत्तिः अभिज्ञाता', framework: 'सम्बद्धं ABS ढाञ्चं अभिज्ञातम्', source: 'समर्थक-स्रोतः प्राप्तः' },
    confidenceSupport: 'प्राप्ताः स्रोताः अस्य विश्लेषणस्य कियत् दृढं समर्थनं कुर्वन्ति', compositeConfidence: 'समग्र-विश्वसनीयता', confidenceScale: 'विश्वसनीयता-मापनम्',
    confidenceFactors: { retrieval_relevance: 'पुनःप्राप्ति-प्रासंगिकता', source_count_factor: 'स्रोतः-संख्या', source_authority: 'स्रोतः-प्रामाणिकता', agreement: 'क्षेत्र-सहमतिः', classification_confidence: 'वर्गीकरण-विश्वसनीयता' },
    confidenceNote: 'अस्मात् विश्लेषणात् प्राप्तानां संकेतानां आधारतः निर्मितः समग्र-अङ्कः।',
    translationUnavailableMessage: 'अनुवाद-सेवा अधुना न उपलभ्यते — आङ्गलभाषा-सन्देशः दृश्यते।', evidenceBoundaryReason: 'प्रमाण-समुच्चयः शून्यः आसीत् अथवा अस्य विश्वसनीयता सीमातः न्यूना आसीत्।',
    sourceLabel: 'स्रोतः', matchLabel: 'मेलने', sourceFields: { authority: 'प्राधिकरणम्', domain: 'क्षेत्रम्', type: 'स्रोतः-प्रकारः', version: 'संस्करणम्', retrieved: 'प्राप्त-दिनाङ्कः', precision: 'सटीकता' }, viewSource: 'स्रोतः पश्यतु',
    builtFor: 'आयुष-मन्त्रालयाय अखिल-भारतीय-आयुर्वेद-संस्थानाय च निर्मितम्', liveEvidenceTrail: 'जीवन्त-प्रमाण-मार्गः', heroTraceTitle: 'उत्पादात् प्रकरणावधि, शृङ्खला स्पष्टा दृश्यते।', heroTraceBody: 'SUTRADHARA प्रश्नं वर्गीकरोति, सम्बद्ध-विधानं दर्शयति, स्रोतं च पश्यति।', citationGrounded: 'उद्धरण-आधारितम्',
    heroTrace: [{ label: 'उत्पाद-प्रश्नः', value: 'नवीन-प्रक्रियया सह अश्वगन्धा-अर्कः' }, { label: 'वर्गीकरणम्', value: 'फाइटोफार्मास्यूटिकल / जैविक-संसाधनम्' }, { label: 'प्रमाण-मार्गः', value: 'जैवविविधता-अधिनियमः, 2002 · धारा 7' }], sourceRetained: 'स्रोतः सुरक्षितः', confidenceHigh: 'विश्वसनीयता: उच्चा',
    focusedTool: 'केन्द्रित-अनुसन्धना-उपकरणम्', working: 'कार्यम् चलति…', absChecklistLabel: 'ABS सूचिका', tkdlPointerLabel: 'TKDL संकेतह्', preview: 'पूर्वावलोकनम्',
    reviewPathway: 'मानव-समीक्षा-मार्गः', escalateTitle: 'IP-सुविधादात्रे प्रेषयतु', escalationDescription: 'विशेषज्ञः अधः प्राप्त-प्रमाणैः सह अस्य प्रश्नस्य समीक्षां करिष्यति।', escalationRecorded: 'एस्केलेशन पञ्जीकृतम्।', escalationFollowUp: 'सुविधादाता भवतः सम्पर्कं करिष्यति।',
    escalationFields: { query: 'प्रश्नः', category: 'वर्गः', jurisdiction: 'क्षेत्राधिकारः', areas: 'क्षेत्राणि', sources: 'स्रोताः' }, noSources: 'किमपि न', contactEmail: 'इमेल (ऐच्छिकम्)', emailPlaceholder: 'you@example.com', escalationError: 'एस्केलेशन-सेवा न प्राप्ता — पुनः प्रयासः क्रियताम्।', cancel: 'निरस्तीकरोतु', sending: 'प्रेष्यते…', submit: 'समर्पयतु',
    graphGrounding: 'उत्तरं कथम् आधारितम् अस्ति', explainabilityGraph: 'व्याख्यात्मक-आलेखः', graphLegend: { query: 'प्रश्न-सन्दर्भः', regulatory: 'नियामक-संरचना', traditional: 'पारंपरिक-ज्ञानम्', authoritative: 'आधिकारिक-स्रोतः' },
    classificationCategories: { 'Classical / Generic Medicine': 'शास्त्रीय / सामान्य औषधम्', 'Patent / Proprietary Medicine': 'पेटेण्ट् / स्वामित्वायुत औषधम्', 'New / Non-Classical Drug': 'नवीन / अशास्त्रीय औषधम्', Phytopharmaceutical: 'फाइटोफार्मास्यूटिकल', 'Ayurveda-Aahar / Nutraceutical': 'आयुर्वेद-आहारः / न्यूट्रास्यूटिकल', Cosmetic: 'सौंदर्यवर्धकम्' }, areaLabels: { Patents: 'पेटेण्ट्-अधिकाराः', 'Geographical Indications': 'भौगोलिक-संकेताः', Trademarks: 'व्यापार-चिह्नानि', Copyright: 'कॉपीराइट-अधिकारः', Designs: 'संरचनाः', 'Trade Secrets': 'व्यापार-रहस्यानि', 'Plant Variety Protection': 'पादप-प्रभेद-संरक्षणम्', 'Traditional Knowledge': 'पारंपरिक-ज्ञानम्', 'Access-and-Benefit-Sharing': 'लाभ-विभाजनम्', 'Drug regulation': 'औषध-नियमनम्', Advertising: 'विज्ञापनम्', Labelling: 'नामपट्टिका-विधानम्', 'Food / nutraceutical regulation': 'खाद्य-नियमनम्', 'Cosmetic regulation': 'सौंदर्यवर्धक-नियमनम्' },
    graphNodes: { product: 'आयुर्वेदिक-उत्पादः', category: 'उत्पाद-वर्गः', tk: 'पारंपरिक-ज्ञानम्', regime: 'IP / नियामक-विधानम्', law: 'शासी नियमः', provision: 'धारा', source: 'आधिकारिक-स्रोतः' }, graphEdges: { product_category: 'सम्बद्धम्', category_regime: 'प्रसंगतम्', category_tk: 'संदर्भितं भवेत्', regime_law: 'नियमेन शासितम्', law_provision: 'धारयति', provision_source: 'स्रोतेन समर्थितम्' },
    eval: { observability: 'प्रणाली-अवलोकनम्', title: 'मूल्याङ्कन-फलकम्', chartLabel: 'विश्वसनीयता-इतिहास-चित्रम्', chartTitle: 'पञ्जीकृत-प्रश्नानां विश्वसनीयता', observations: 'अवलोकनानि', chartEmpty: 'प्रथमान् विश्लेषणोत्तरं इतिहासः दृश्यते।', queryStart: 'प्रश्नः 01', queryLatest: 'नवीनतमः प्रश्नः', totalQueries: 'कुल-पञ्जीकृत-प्रश्नाः', safeAbstention: 'सुरक्षित-त्याग-दरः', averageConfidence: 'औसत-विश्वसनीयता', answerAccuracy: 'उत्तर-सटीकता', citationCorrectness: 'उद्धरण-शुद्धता', classificationAccuracy: 'वर्गीकरण-सटीकता', multilingualQuality: 'बहुभाषीय-उत्तर-गुणवत्ता', pending: 'मूल्याङ्कनम् अवशिष्टम्', manualReviewSet: 'मूल्याङ्कनम् अवशिष्टम् — समीक्षा आवश्यकी', manualReview: 'मूल्याङ्कनम् अवशिष्टम्', emptyTitle: 'भवतः प्रमाण-मार्गः अत्र आरभते।', emptyBody: 'विश्लेषणं चालयतु।', citationReview: 'उद्धरण-समीक्षा', note: 'मूल्याङ्कनम् अवशिष्टम्।' },
  },
}
